apiVersion: v1
kind: ServiceAccount
metadata:
  name: dvwa-sa
  namespace: dvwa-apps
---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-service
  labels:
    app: avi-gslb
  namespace: dvwa-apps
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: dvwa-apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa-apps
  namespace: dvwa-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvwa-apps
  template:
    metadata:
      labels:
        app: dvwa-apps
    spec:
      containers:
      - name: web-dvwa
        image: vulnerables/web-dvwa
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      serviceAccountName: dvwa-sa
      imagePullSecrets:
      - name: regcred
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dvwa-ingress
  labels:
    app: avi-gslb
  namespace: dvwa-apps
spec:
  tls:
  - hosts:
      - dvwa.apps.acepod.com
    secretName: dvwa-ingress-tls
  rules:
    - host: dvwa.apps.acepod.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: dvwa-service
            servicePort: 80
