apiVersion: v1
kind: Service
metadata:
  name: dvwa-service
  labels:
    app: avi-gslb
spec:
  type: LoadBalancer
  externalIPs:
  - 172.16.10.51
  ports:
  - name: http
    port: 8080
    targetPort: 80
  selector:
    app: dvwa-apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvwa-apps
  template:
    metadata:
      labels:
        app: dvwa-apps
    spec:
      containers:
      - name: web-dvwa
        image: vulnerables/web-dvwa
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
